set shell := ["bash", "-c"]

# One-shot target for pre-commit checks
precommit: fmt-check lint build check-tests

# Check formatting of all project files
fmt-check:
	cargo +nightly fmt --all --check
	taplo fmt --check
	deno fmt --check ../.github/**/*.yaml ../.github/**/*.yml ../docs/{testnet,sidechain}.md

# Format all project files
fmt:
	cargo +nightly fmt --all
	taplo fmt
	deno fmt ../.github/**/*.yaml ../.github/**/*.yml ../docs/{testnet,sidechain}.md

# Lint all components
lint:
	cargo +nightly clippy --tests -- -D warnings
	forge lint
	typos --exclude solidity/lib --config ../.github/typos.toml

# Build artifacts
build:
	cargo build --workspace
	forge build

# Run test suites
check-tests:
	cargo nextest run --workspace
	forge test
